### PR TITLE
Fix bottom of some modals being cut off

### LINKED ISSUE #3103: [Bug]: Bottom of some modals not visible on laptop sized screens
### What happened?

image

### How?

open liquidity removal modal on laptop sized screen

### What was Expected?

modal should be centered on screen

### Relevant log output

_No response_

### What browser(s) are you seeing the problem on?

_No response_

### What wallet are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by surudhb**
### Describe your changes 
_Describe the purpose + content of these changes_
- Removing the "pushdown" from top bias that modals used to have and instead vertically centering them so that they don't get cut off on smaller laptop screens

### Link the related issue
Closes #3103

### Checklist before requesting a review
- [x] Is this PR ready for merge? (Please convert to a draft PR otherwise)
- [x] I have performed a self-review of my code.
- [x] Did I request feedback from a team member prior to merge? 
- [x] Does my code following the style guide at `docs/CODING-STYLE.md`?

### Instructions for Reviewer
**Functionalities or workflows that should specifically be tested.**

1.

2.

**Environmental conditions which may result in expected but differential behavior.**

1.

2.

### If relevant, list additional work to complete pre-merge (delete logging, code abstraction, etc)

### CODE REVIEW

File: src/contexts/ENSAddressContext.tsx [hunk 1]
```diff
@@ -49,7 +49,7 @@ export const ENSAddressContextProvider = (props: { children: ReactNode }) => {
                 const batchedEnsMap = await fetchEnsAddresses(
                     uncachedAddresses,
                 );
-                console.log({ uncachedAddresses });
+
```
Comment (surudhb) [inline src/contexts/ENSAddressContext.tsx:52]: cleaning up leftover log

**Review by benwolski — APPROVED** [review]
looks great!
